offset=[90,0]
#offset=[0,0]
unit="mm"
size=[75,50]
dpmm=8

[[image]]
  file="biowatch.png"
  size=[15,0]
  position=[1,23]
  darkness=50000

[[image]]
  file="biohazard.png"
  size=[20,0]
  position=[54,28]
  darkness=50000


[[qr]]
  input=0
  position=[0,3]
  size=[30,30]
  center=true
