offset=[90,0]
#offset=[0,0]
unit="mm"
size=[75,50]
dpmm=8


[[image]]
file="biowatch.png"
properties = {
    size=[15,0],
    position=[1,-5],
    darkness=50000,
    left=true,
    bottom=true }

[[image]]
file="biohazard.png"
properties = {
    size=[20,0],
    position=[-1,-5],
    darkness=50000,
    right=true,
    bottom=true }

[[text]]
value="testing"
properties= {
    position=[0,0],
    center = true,
    top = true}


[[qr]]
input=0
properties = {
    position=[0,3],
    size=[30,30],
    center=true}
