offset=[90,0]
#offset=[0,0]
unit="mm"
size=[75,50]
dpmm=8


[[image]]
file="biowatch.png"
properties = {
    size=[15,0],
    position=[1,-10],
    darkness=50000,
    left=true,
    bottom=true }

[[image]]
file="biohazard.png"
properties = {
    size=[20,0],
    position=[-1,-10],
    darkness=50000,
    right=true,
    bottom=true }

[[text]]
input=1
font="fonts/Nunito-Regular.ttf"
fontsize=24.0
properties= {
    position=[0,0],
    center = true,
    top = true }


[[qr]]
input=0
properties = {
    position=[0,-1],
    size=[30,30],
    center=true}

[[code128]]
input=1
properties = {
    position=[0,0],
    size=[0,10],
    center=true,
    bottom=true}
 
